display_name: FlClash-Meow

icon: ./assets/images/icon.svg

keywords:
  - FlClash-Meow
  - Clash
  - ClashMeta
  - meow-rs
  - Proxy

supported_mime_type:
  - x-scheme-handler/flclash-meow

generic_name: FlClash-Meow

categories:
  - Network

startup_notify: true
startup_wm_class: com.yukko.flclashmeow

include: []
